spring:
  application:
    name: webflux
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 9090
  address: 0.0.0.0

scheduler:
  enabled: true
  max-allow-user-count: 1000
